# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_walnut', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='name',
            new_name='Useremail',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='active',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='PatientID',
            field=models.IntegerField(default='00001', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
