# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_walnut', '0002_auto_20180328_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='PatientID',
            field=models.IntegerField(default='00001', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
