# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_walnut', '0003_auto_20180328_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='PatientID',
            field=models.IntegerField(default=0, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
